---
- hosts: zookeeper
  remote_user: root
  tasks:
      - name: download zookeeper
        get_url: url=http://apache.mirrors.pair.com/zookeeper/zookeeper-3.4.6/zookeeper-3.4.6.tar.gz dest=/home/ubuntu/zookeeper.tar.gz mode=0440
      - unarchive: src=/home/ubuntu/zookeeper.tar.gz dest=/home/ubuntu/ copy=no
      - copy: src=/N/u/oliveral/465-oliverlewis/project/zoo.cfg dest=/home/ubuntu/zookeeper-3.4.6/conf/zoo.cfg mode=0644
      - command: /home/ubuntu/zookeeper-3.4.6/bin/zkServer.sh start

- hosts: nimbus
  remote_user: root
  tasks:
    - name: Import the public key used by the package management system
      apt_key: keyserver=hkp://keyserver.ubuntu.com:80 id=7F0CEB10 state=present
    - name: storm release
      get_url: url=http://apache.mirrors.pair.com/storm/apache-storm-0.9.4/apache-storm-0.9.4.tar.gz dest=/home/ubuntu/stormv0.9.4.tar.gz mode=0440
    - unarchive: src=/home/ubuntu/stormv0.9.4.tar.gz dest=/home/ubuntu/ copy=no
    - command: /home/ubuntu/apache-storm-0.9.4/bin/storm nimbus
      poll: 0
    - command: /home/ubuntu/apache-storm-0.9.4/bin/storm ui
      poll: 0
  

