---
- hosts: ansible-test
  remote_user: root
  tasks:
    - name: Import the public key used by the package management system
      apt_key: keyserver=hkp://keyserver.ubuntu.com:80 id=7F0CEB10 state=present
    - name: apache install
      apt: pkg=apache2 state=latest update_cache=yes
      notify:
      - start apache2
  handlers:
    - name: start apache2
      service: name=apache2 state=started
